export const formations = {
    '4-3-3': {
        name: '4-3-3 Attaque',
        system: '4-3-3',
        description: 'Formation offensive avec trois attaquants et un milieu équilibré',
        strengths: ['Pression haute', 'Jeu de passes', 'Largeur offensive'],
        weaknesses: ['Milieu exposé', 'Contre-attaques'],
        famousTeams: ['Barcelona (Guardiola)', 'Liverpool (Klopp)', 'Bayern Munich'],
        positions: [
            { position: 'GK', x: 8, y: 50, role: 'Gardien' },
            { position: 'RB', x: 23, y: 18, role: 'Arrière Droit' },
            { position: 'CB', x: 23, y: 38, role: 'Défenseur Central' },
            { position: 'CB', x: 23, y: 62, role: 'Défenseur Central' },
            { position: 'LB', x: 23, y: 82, role: 'Arrière Gauche' },
            { position: 'CDM', x: 42, y: 35, role: 'Milieu Défensif' },
            { position: 'CM', x: 42, y: 50, role: 'Milieu Central' },
            { position: 'CM', x: 42, y: 65, role: 'Milieu Central' },
            { position: 'RW', x: 72, y: 23, role: 'Ailier Droit' },
            { position: 'ST', x: 72, y: 50, role: 'Avant-Centre' },
            { position: 'LW', x: 72, y: 77, role: 'Ailier Gauche' },
        ],
    },
    '4-4-2': {
        name: '4-4-2 Classique',
        system: '4-4-2',
        description: 'Formation équilibrée et solide, idéale pour la transition',
        strengths: ['Équilibre', 'Compacité', 'Duo d\'attaquants'],
        weaknesses: ['Manque de créativité', 'Milieu surchargé'],
        famousTeams: ['Manchester United (Ferguson)', 'Atletico Madrid (Simeone)'],
        positions: [
            { position: 'GK', x: 8, y: 50, role: 'Gardien' },
            { position: 'RB', x: 23, y: 18, role: 'Arrière Droit' },
            { position: 'CB', x: 23, y: 38, role: 'Défenseur Central' },
            { position: 'CB', x: 23, y: 62, role: 'Défenseur Central' },
            { position: 'LB', x: 23, y: 82, role: 'Arrière Gauche' },
            { position: 'RM', x: 50, y: 18, role: 'Milieu Droit' },
            { position: 'CM', x: 50, y: 38, role: 'Milieu Central' },
            { position: 'CM', x: 50, y: 62, role: 'Milieu Central' },
            { position: 'LM', x: 50, y: 82, role: 'Milieu Gauche' },
            { position: 'ST', x: 75, y: 38, role: 'Avant-Centre' },
            { position: 'ST', x: 75, y: 62, role: 'Avant-Centre' },
        ],
    },
    '4-2-3-1': {
        name: '4-2-3-1 Moderne',
        system: '4-2-3-1',
        description: 'Formation très populaire avec double pivot défensif',
        strengths: ['Protection défensive', 'Flexibilité', 'Transitions rapides'],
        weaknesses: ['Isolement de l\'attaquant', 'Largeur limitée'],
        famousTeams: ['Real Madrid', 'Chelsea', 'Juventus'],
        positions: [
            { position: 'GK', x: 8, y: 50, role: 'Gardien' },
            { position: 'RB', x: 23, y: 18, role: 'Arrière Droit' },
            { position: 'CB', x: 23, y: 38, role: 'Défenseur Central' },
            { position: 'CB', x: 23, y: 62, role: 'Défenseur Central' },
            { position: 'LB', x: 23, y: 82, role: 'Arrière Gauche' },
            { position: 'CDM', x: 40, y: 38, role: 'Milieu Défensif' },
            { position: 'CDM', x: 40, y: 62, role: 'Milieu Défensif' },
            { position: 'RW', x: 60, y: 20, role: 'Ailier Droit' },
            { position: 'CAM', x: 60, y: 50, role: 'Meneur de Jeu' },
            { position: 'LW', x: 60, y: 80, role: 'Ailier Gauche' },
            { position: 'ST', x: 78, y: 50, role: 'Avant-Centre' },
        ],
    },
    '3-5-2': {
        name: '3-5-2',
        system: '3-5-2',
        description: 'Formation avec trois défenseurs et pistons offensifs',
        strengths: ['Domination milieu', 'Largeur', 'Duo d\'attaquants'],
        weaknesses: ['Vulnérable sur les ailes', 'Pistons doivent beaucoup courir'],
        famousTeams: ['Inter Milan (Conte)', 'Atalanta'],
        positions: [
            { position: 'GK', x: 8, y: 50, role: 'Gardien' },
            { position: 'CB', x: 23, y: 27, role: 'Défenseur Central Droit' },
            { position: 'CB', x: 23, y: 50, role: 'Défenseur Central' },
            { position: 'CB', x: 23, y: 73, role: 'Défenseur Central Gauche' },
            { position: 'RWB', x: 45, y: 12, role: 'Piston Droit' },
            { position: 'CDM', x: 45, y: 35, role: 'Milieu Défensif' },
            { position: 'CM', x: 45, y: 50, role: 'Milieu Central' },
            { position: 'CDM', x: 45, y: 65, role: 'Milieu Défensif' },
            { position: 'LWB', x: 45, y: 88, role: 'Piston Gauche' },
            { position: 'ST', x: 75, y: 38, role: 'Avant-Centre' },
            { position: 'ST', x: 75, y: 62, role: 'Avant-Centre' },
        ],
    },
};

export const getFormation = (name) => formations[name];
export const getFormationsList = () => Object.keys(formations);
export const getFormationsOptions = () => Object.entries(formations).map(([key, value]) => ({
    value: key,
    label: value.name,
    system: value.system,
}));
